// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNNmPF47TSlPgppF8AgmW4Q6vE6ireNfM',
    appId: '1:429631835955:web:367d4a87cabc541ccfb846',
    messagingSenderId: '429631835955',
    projectId: 'my-notes-b54c1',
    authDomain: 'my-notes-b54c1.firebaseapp.com',
    storageBucket: 'my-notes-b54c1.appspot.com',
    measurementId: 'G-WV8WTNSCYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5IHDIh2JdSbZgbuWRRqS4sAV-QHL_l0E',
    appId: '1:429631835955:android:231ed5ee0d2ca408cfb846',
    messagingSenderId: '429631835955',
    projectId: 'my-notes-b54c1',
    storageBucket: 'my-notes-b54c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKMlKP6Tggtyi5sYlTBTmxKUNJTbRzpmc',
    appId: '1:429631835955:ios:46700ad1c0dcec70cfb846',
    messagingSenderId: '429631835955',
    projectId: 'my-notes-b54c1',
    storageBucket: 'my-notes-b54c1.appspot.com',
    iosClientId: '429631835955-rukgd524makh36fh7b0ag37e2milm4v2.apps.googleusercontent.com',
    iosBundleId: 'net.flame.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKMlKP6Tggtyi5sYlTBTmxKUNJTbRzpmc',
    appId: '1:429631835955:ios:46700ad1c0dcec70cfb846',
    messagingSenderId: '429631835955',
    projectId: 'my-notes-b54c1',
    storageBucket: 'my-notes-b54c1.appspot.com',
    iosClientId: '429631835955-rukgd524makh36fh7b0ag37e2milm4v2.apps.googleusercontent.com',
    iosBundleId: 'net.flame.mynotes',
  );
}
