// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxPiK4wHHQBZfaxL2Cvdt79PVWYHx4iK4',
    appId: '1:835453479319:web:de6ad3455e0c33c0cbfcd2',
    messagingSenderId: '835453479319',
    projectId: 'mynotes2',
    authDomain: 'mynotes2-cd672.firebaseapp.com',
    storageBucket: 'mynotes2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC8rwjOGDNg2TqA8cF2u6M4AuwaOmLEus',
    appId: '1:835453479319:android:830725d10113673dcbfcd2',
    messagingSenderId: '835453479319',
    projectId: 'mynotes2',
    storageBucket: 'mynotes2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrliJBx_3QR5hVf5xY_uTmc2UJrmj0aY4',
    appId: '1:835453479319:ios:ed66a04a54ba7aabcbfcd2',
    messagingSenderId: '835453479319',
    projectId: 'mynotes2',
    storageBucket: 'mynotes2.appspot.com',
    iosClientId: '835453479319-fjrcbdv6mv5tvmjrtapcrutbrtiju0ft.apps.googleusercontent.com',
    iosBundleId: 'net.flame.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrliJBx_3QR5hVf5xY_uTmc2UJrmj0aY4',
    appId: '1:835453479319:ios:ed66a04a54ba7aabcbfcd2',
    messagingSenderId: '835453479319',
    projectId: 'mynotes2',
    storageBucket: 'mynotes2.appspot.com',
    iosClientId: '835453479319-fjrcbdv6mv5tvmjrtapcrutbrtiju0ft.apps.googleusercontent.com',
    iosBundleId: 'net.flame.mynotes',
  );
}
